version: '3'

services:
  hass:
    network_mode: host
    hostname: ha_example
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
